name: Mac

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-13
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --all-targets --all-features --verbose
      - name: Try auto-download
        run: cargo run --example download_ffmpeg
